version: 2.1
orbs:
  node: circleci/node@4.1.0
  terraform: circleci/terraform@3.1.0
  azure-cli: circleci/azure-cli@1.2.2
jobs:
  azure-deployment: 
    executor: node/default
    steps:
      - checkout 
      - azure-cli/install
      - run:
          name: Install Azure functions tools
          command: sudo npm i -g azure-functions-core-tools@3 --unsafe-perm true
      - run:
          name: azure login
          command: az login --service-principal -u $CLIENT_ID -p $CLIENT_SECRET --tenant "${AZURE_TENANT}" 
      - run:
          name: azure functions list
          command: az functionapp list
      - run:
          name: deploying to function app 
          command: func azure functionapp publish $FUNCTION_APP_NAME 


         
workflows:
  function-deployment: 
    
    jobs:
      -  azure-deployment
