
version: 2.1
orbs:
  python: circleci/python@1.5.0
  terraform: circleci/terraform@3.1.0
  azure-cli: circleci/azure-cli@1.2.2
jobs:
  azure-deployment: 
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout 
      - azure-cli/install
      - run:
          name: azure login
          command: az login --tenant "${AZURE_TENANT}"

         


workflows:
  function-deployment: 
    
    jobs:
      -  azure-deployment
